// lib/servicesData.ts

export const services = [
  {
    slug: "extraction",
    title: "Extraction (দাঁত তোলা)",
    icon: "chip_extraction",
    img: "/extraction.webp",
    desc: "Safe removal of damaged or infected teeth under local anesthesia.",
    duration: "30-60 Min",
    desc1: "Safe and painless tooth removal by experienced dental surgeons.",
    desc2: "দাঁত তোলা একটি নিরাপদ প্রক্রিয়া যা অভিজ্ঞ ডাক্তাররা করে থাকেন।",
    prices: [
      { name: "Front Tooth (সামনের দাঁত)", price: 400 },
      { name: "Back Tooth (পিছনের দাঁত)", price: 600 },
      { name: "Broken Tooth (ভাঙা দাঁত)", price: 600 },
      { name: "Wisdom Tooth – Surgery (আক্কেল দাঁত - সার্জারি)", price: "1500-3000" },
      { name: "Milk Tooth (দুধ দাঁত)", price: 200 },
    ],
  },
  {
    slug: "scaling",
    title: "Scaling (দাঁত পরিষ্কার করা)",
    icon: "cleaning_services",
    img: "/scaling.jpeg",
    desc: "Professional cleaning to remove plaque and tartar from teeth surfaces.",
    duration: "30-45 Min",
    desc1: "Dental scaling removes tartar and plaque from teeth surfaces and beneath the gumline.",
    desc2: "দাঁত স্কেলিং বা পরিষ্কার করা একটি গুরুত্বপূর্ণ চিকিৎসা যা দাঁতের গোড়ায় জমে থাকা শক্ত পাথর এবং জীবাণু অপসারণ করে।",
    prices: [{ name: "Scaling", price: 800 }],
  },
  {
    slug: "polishing",
    title: "Polishing (দাঁত পালিশ করা)",
    icon: "auto_fix_high",
    img: "/polishing.jpg",
    desc: "Teeth polishing treatment that improves shine and removes surface stains.",
    duration: "30 Min",
    desc1: "Polishing helps remove surface stains and enhances shine of teeth.",
    desc2: "দাঁত পালিশ করা দাঁতের উজ্জ্বলতা বাড়ায় এবং দাগ দূর করে।",
    prices: [{ name: "Polishing", price: 500 }],
  },
  {
    slug: "removal_partial_denture",
    title: "Removable Partial Denture",
    icon: "dentistry",
    img: "denture.jpg",
    desc: "Custom removable denture used to replace one or multiple missing teeth.",
    duration: "Varies",
    desc1: "Partial dentures replace missing teeth for better chewing and smile.",
    desc2: "আংশিক দন্তপ্রতিস্থাপন খাবার চর্বণ ও হাসি ঠিক রাখতে সাহায্য করে।",
    prices: [
      { name: "Indian", price: 500 },
      { name: "China", price: 700 },
      { name: "Pakistan", price: 800 },
      { name: "Japan", price: 1000 },
      { name: "Flexible", price: "Discuss" },
      { name: "Crystal", price: 1000 },
    ],
  },
  {
    slug: "filling",
    title: "Filling (দাঁতের ভরা)",
    icon: "ink_eraser",
    img: "/filling.webp",
    desc: "Composite fillings used to restore cavities and prevent tooth decay.",
    duration: "30-60 Min",
    desc1: "Fillings restore teeth affected by cavities and prevent further decay.",
    desc2: "ফিলিং দাঁতের ক্ষয় প্রতিরোধ করে এবং ক্ষতিগ্রস্ত অংশ পূরণ করে।",
    prices: [
      { name: "Astrai Filling", price: 200 },
      { name: "Silver Amalgam Alloy", price: 1000 },
      { name: "Copper Amalgam", price: 600 },
      { name: "Auto Glass Ionomer (Japan)", price: 500 },
      { name: "Light Cure Glass Ionomer (Japan)", price: 800 },
      { name: "Composite Anterior", price: 1000 },
      { name: "Composite Posterior", price: 1500 },
      { name: "Pulp Capping", price: 2000 },
      { name: "Post RCT Glass Ionomer (Japan)", price: 1000 },
    ],
  },
  {
    slug: "complete_denture",
    title: "Complete Denture (পূর্ণ দাঁত প্রতিস্থাপন)",
    icon: "health_and_safety",
    img: "/complete.jpg",
    desc: "Full denture replacement designed for patients missing all teeth.",
    duration: "Varies",
    desc1: "Complete dentures fully replace missing teeth for functional and aesthetic purposes.",
    desc2: "পূর্ণ দন্তপ্রতিস্থাপন সমস্ত দাঁত হারানো রোগীদের জন্য কার্যকর ও সুন্দর সমাধান।",
    prices: [
      { name: "Hcat Cure-Lab per site (Pakistan)", price: 10000 },
      { name: "Hcat Cure-Lab per site (Japan)", price: 12000 },
    ],
  },
  {
    slug: "root_canal_treatment",
    title: "Root Canal Treatment (মূল রুট চিকিৎসা)",
    icon: "pulse_alert",
    img: "/rootcanal.jpg",
    desc: "Procedure to treat infected tooth pulp and save the natural tooth.",
    duration: "60-90 Min",
    desc1: "Root canal treatment removes infected pulp and preserves natural tooth.",
    desc2: "মূল রুট চিকিৎসা সংক্রমিত পলপ অপসারণ করে এবং স্বাভাবিক দাঁত সংরক্ষণ করে।",
    prices: [
      { name: "Anterior Tooth", price: 1200 },
      { name: "Posterior Tooth", price: 1500 },
      { name: "Anterior by Endomotor", price: 1800 },
      { name: "Posterior by Endomotor", price: 2500 },
      { name: "Re Root Canal Treatment", price: 3000 },
    ],
  },
  {
    slug: "crown",
    title: "Crown (দাঁতের ক্রাউন)",
    icon: "brightness_5",
    img: "/crown.jpg",
    desc: "Dental cap placed over a damaged tooth to restore strength and shape.",
    duration: "45-60 Min",
    desc1: "Crown restores strength, shape, and aesthetics of a damaged tooth.",
    desc2: "ক্রাউন ক্ষতিগ্রস্ত দাঁতের শক্তি, আকার ও সৌন্দর্য পুনরুদ্ধার করে।",
    prices: [
      { name: "Porcelain/Metal (per unit)", price: 2000 },
      { name: "Shofa/Collar Band (per unit)", price: 3000 },
      { name: "Zirconium (per unit)", price: "Discuss" },
    ],
  },
  {
    slug: "pulpotomy_pulpectomy",
    title: "Pulpotomy & Pulpectomy",
    icon: "child_care",
    img: "/pulpotomy.webp",
    desc: "Root treatments for infected primary teeth commonly used in children.",
    duration: "45-60 Min",
    desc1: "Pulp treatments for children to save infected primary teeth.",
    desc2: "শিশুদের সংক্রমিত প্রাথমিক দাঁত সংরক্ষণ করতে পলপ চিকিৎসা।",
    prices: [
      { name: "Pulpotomy per tooth", price: 2000 },
      { name: "Pulpectomy per tooth", price: 2000 },
    ],
  },
  {
    slug: "operculectomy",
    title: "Operculectomy",
    icon: "content_cut",
    img: "/operculectomy.webp",
    desc: "Minor surgical procedure to remove excess gum covering a tooth.",
    duration: "30 Min",
    desc1: "Operculectomy removes excess gum tissue covering a tooth.",
    desc2: "অতিরিক্ত মাড়ি সরিয়ে দাঁত পরিষ্কার করার ছোট সার্জারি।",
    prices: [{ name: "Operculectomy per tooth", price: 1000 }],
  },
  {
    slug: "grinding_dressing",
    title: "Grinding & Dressing",
    icon: "build_circle",
    img: "/dressing.jpg",
    desc: "Grinding sharp tooth edges and applying medicated dressing for relief.",
    duration: "30 Min",
    desc1: "Grinding sharp edges and applying soft dressing for relief.",
    desc2: "তীক্ষ্ণ দাঁতের ধার পালিশ এবং নরম ড্রেসিং প্রয়োগ।",
    prices: [
      { name: "Grinding/Curatage", price: 300 },
      { name: "Soft Dressing Fee", price: 300 },
    ],
  },
  {
    slug: "midline_diastema_closure",
    title: "Midline Diastema Closure",
    icon: "align_center",
    img: "/midline.jpg",
    desc: "Cosmetic treatment to close gaps between front teeth.",
    duration: "Varies",
    desc1: "Treatment to close gaps between front teeth.",
    desc2: "সামনের দাঁতের ফাঁক বন্ধ করার চিকিৎসা।",
    prices: [{ name: "Pair Gap", price: "Discuss" }],
  },
];